/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    projects: Project;
    media: Media;
    users: User;
    clients: Client;
    posts: Post;
  };
  globals: {};
}
export interface Project {
  id: string;
  title: string;
  slug?: string;
  logo?: string | Media;
  location: string;
  buildDate: string;
  images?: {
    view: 'Front view' | 'Back view' | 'Left side' | 'Right side' | 'Top view' | 'Interior view' | 'Other';
    label?: string;
    image: string | Media;
    id?: string;
    blockName?: string;
    blockType: 'project-view';
  }[];
  layout?: {
    content?: {
      [k: string]: unknown;
    }[];
    id?: string;
    blockName?: string;
    blockType: 'content';
  }[];
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
  };
  client?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  photo?: string | Media;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Client {
  id: string;
  name: string;
  logo: string | Media;
  url?: string;
  showInCarousel?: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Post {
  id: string;
  title: string;
  image: string | Media;
  excerpt: {
    [k: string]: unknown;
  }[];
  content: (
    | {
        bannerFields: {
          type?: 'default' | 'success' | 'warning' | 'error';
          addCheckmark?: boolean;
          content: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'banner';
      }
    | {
        blogContentFields: {
          richText: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'blogContent';
      }
    | {
        blogMarkdownFields: {
          markdown: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'blogMarkdown';
      }
    | {
        mediaBlockFields: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
  )[];
  slug?: string;
  author: string | User;
  publishedOn: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
